### ISSUE TITLE
Combine and Minify JavaScript Files

### ISSUE THREAD

**Issue by gordonbanderson** [gordonbanderson/Mappable#11]
Now using 3 files:
* Map Utility
* Clusterer
* Full Screen
Combining them makes sense

**Comment by wernerkrauss** [comment]
Either grunt or maybe better: Requirements::combine_files()... the latter needs the /assets/cache/ dir writeable on the user side.

**Comment by gordonbanderson** [comment]
I went with the Grunt option (after learning how to), seems to work well.  Flag added to toggle compressed JS or not, using uglify halves the size of the combined file.  Pushed to 3.1 branch
