### ISSUE TITLE
StaticMap doesn't respect getMappableMapPin

### ISSUE THREAD

**Issue by wernerkrauss** [gordonbanderson/Mappable#22]
there should be a way to get the custom map pin on a static map, see https://developers.google.com/maps/documentation/staticmaps/?hl=de#MarkerStyles

**Comment by gordonbanderson** [comment]
I haven't used the static map option to be honest.  https://developers.google.com/maps/documentation/staticmaps/?hl=en#MarkerStyles is easier for me to understand also :)

URL length is also an issue with that wonderful browser, Internet Explorer, see http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers (max of 2083 chars)

**Comment by wernerkrauss** [comment]
OK, i guess we won't get a single url with more than 2000 chars, not with just one marker. But good to know / remember that.
