### ISSUE TITLE
Move Points of Interest to a Separate Module

### ISSUE THREAD

**Issue by gordonbanderson** [gordonbanderson/Mappable#27]
I am now leaning towards moving Points of Interest to a separate module, as there are times that you want to use maps on a website but do not require the Point of Interest functionality, thus unnecessarily cluttering up the CMS with extra options.

Thoughts?

**Comment by wernerkrauss** [comment]
good idea, you can suggest it in mappable composer.json...

for my updated projects i don't need that functionality.

**Comment by gordonbanderson** [comment]
Thanks for the +1 - I only realised the issue when I was dealing with another site that only needed the maps.  Will separate the POI functionality into a separate module.

**Comment by gordonbanderson** [comment]
Done, see https://github.com/gordonbanderson/MappablePointsOfInterest

**Comment by Sanderha** [comment]
Sorry for opening this up again, but it seems this module still has the POIMapPage pagetype in it. Why is that?
It seems quite annoying having to remove this each time, when you only need the maps functionality

**Comment by gordonbanderson** [comment]
Fair enough to bring it up as it is a bug.  Best to create a new tracker issue though :)

I've moved the files POIMapPage.php and POIMapPage.ss from Mappable to MappablePointsOfInterest as requested.

**Comment by Sanderha** [comment]
Alright cool, thanks! :)
