### ISSUE TITLE
Multiple markers on one map

### ISSUE THREAD

**Issue by Sanderha** [gordonbanderson/Mappable#28]
Is it possible to select certain dataobjects with the map extension, and make them appear on one google map?

**Comment by gordonbanderson** [comment]
The Map Extension is purely for the purposes of rendering the icons on a map, any selection criteria you will have to add yourself.  Have a look at http://demo.weboftalent.asia/mappable/map-from-a-datalist-unclustered/

Whilst in this case I was showing Flickr images, line 1 of https://gist.github.com/gordonbanderson/5299266#file-pagewithmap-php could for example be changed to 

```php
$flickrPhotos = DataList::create( 'FlickrPhoto' )->filter('ShowPhotoOnAMap', true);
```

If a boolean field ShowPhotoOnAMap was added to FlickrPhoto, then a tickbox in the CMS would determine whether or not to show the photo.

**Comment by Sanderha** [comment]
Oh i see now that it is in the docs. Sorry man!

Thanks a lot for the help, and awesome module
