### ISSUE TITLE
Can not disable clusterer

### ISSUE THREAD

**Issue by Sanderha** [gordonbanderson/Mappable#29]
Hey I am trying to disable the clustering functionality.

using 
```php
$map->setClusterer( false );
```
Does not disable it. Even when I go directly to MapGoogleJS and set the useclusterer to false, it still clusters. Even the JS data-useclusterer attribute is set to false, but it still clusters..

What is going on?

**Comment by gordonbanderson** [comment]
I can replicate the bug.  It seems there is a second problem in that if clustering is correctly disabled then no markers show at all.

**Comment by Sanderha** [comment]
To work around this, I ended up editing the module itself, in the maputil.js file, line 345.
I added the following:
```javascript
				markerCluster.setMaxZoom(1);
				markerCluster.setGridSize(1);
				markerCluster.redraw();
```

Which is not very nice I know, but I didnt have time to really mess with it much

**Comment by gordonbanderson** [comment]
I've tested this toggling clustering on a POIMapPage I am running locally and it is now behaving as expected.

Thanks for reporting the issue.

**Comment by Sanderha** [comment]
Very nice, thanks!
