### ISSUE TITLE
Clusterer: merge info windows for cluster

### ISSUE THREAD

**Issue by wernerkrauss** [gordonbanderson/Mappable#5]
so you can see the info windows for all clustered map pins at once.

Maybe http://stackoverflow.com/questions/6047304/marker-clusterer-merging-markers-info-window-content is a way to go?

**Comment by gordonbanderson** [comment]
I've implemented https://github.com/googlemaps/js-marker-clusterer in development, and it's possible to see map pins that are very close together (likes of a few metres)
